[sources.github]
access_token = "<github-pat>"

[destination.filesystem.credentials]
type                       = "azure"
azure_storage_account_name = "<storage-account-name>"
azure_storage_account_key = "<storage-account-key>"  # or replace with sas_token="<sas-token>"
